### ISSUE TITLE
Allow configless programmatic only creation of MinioClient

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-minio#178]
Before https://github.com/quarkiverse/quarkus-minio/pull/166 the named scenario was possible and we have been relying on it in Camel Quarkus. 

After https://github.com/quarkiverse/quarkus-minio/pull/166 it [does not work anymore](https://github.com/apache/camel-quarkus/issues/4328)

Could you please make config of the default client optional so that we can create the client 100% programmatically without any config in `application.properties`?

**Comment by ppalaga** [comment]
BTW, what we ask for is a common principle accepted in many Quarkiverse extensions.

**Comment by jtama** [comment]
Have you tried : 
`quarkus.minio.enabled=false` ?

**Comment by jtama** [comment]
I have to chew on that and check if I can get back to the former behaviour withou having to split all (that would take more time I think).

**Comment by ppalaga** [comment]
BTW, if B. should become the prefered solution, I could prepare a PR.

**Comment by jtama** [comment]
Well B would be a problem as devservices needs to be aware of the needed minioClient... So the solution would be to only leave native cooking in the core... Unless I miss something...

**Comment by jtama** [comment]
Just for me to be sure. Before this change the property `quarkus.minio.allow-empty` had to be set to true, to enable your case (which are perfectly get). How did you do that before ? 

If i re-add the allow-empty (which would only be activated if no other config is set), would it be good for you ? 

There we have to choice : 

- It's a compile config value (I am pretty sure it won't suits you)
- It's a runtime config, but you will still need to disable devservices

**Comment by ppalaga** [comment]
> Before this change the property quarkus.minio.allow-empty had to be set to true, to enable your case (which are perfectly get). How did you do that before ?

Indeed, we have been passing `RunTimeConfigurationDefaultBuildItem("quarkus.minio.allow-empty", "true")` programmatically.

> If i re-add the allow-empty (which would only be activated if no other config is set

"would only be activated" - you mean the need for `quarkus.minio.allow-empty=true` could be autodetected by quarkus-minio?

> would it be good for you?

Having `quarkus.minio.allow-empty=true` working the way it did before would definitely be better than the current state and we could live with it.

But still, passing `quarkus.minio.allow-empty=true` from our extension may clash with end user expectations about how much safety they have about not forgetting to set `quarkus.minio.url`. I'd personally find splitting into core and client a bit cleaner. But of course the decision is up to you.

**Comment by jtama** [comment]
I definitely like the second option best, but in this case it would be more like quarkus-minio-native...

**Comment by jtama** [comment]
Sometime today 👍.

**Comment by jtama** [comment]
@ppalaga It's released!

**Comment by ppalaga** [comment]
Thanks!
