### ISSUE TITLE
Upgrade to Quarkus 3.0.0

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-minio#193]
I started migrating Camel Quarkus to Quarkus 3.0.0. I wonder whether there is any plan or known issues for doing the same in quarkus-minio?

**Comment by jtama** [comment]
Absolutely, there is already a tentative migration in branch [prepare-v3](https://github.com/quarkiverse/quarkus-minio/tree/prepare-v3).

I think, I will soon create a branch for Quarkus 2.x maintainance and merge this one main. Will let you know as soon as it's done.

**Comment by ppalaga** [comment]
> there is already a tentative migration in branch [prepare-v3](https://github.com/quarkiverse/quarkus-minio/tree/prepare-v3).

Great news, thanks!

How complete is the branch? Is there any chance to get some early Alpha release?

**Comment by jtama** [comment]
It worked when I did the job, I need to migrate to 3.0.0Alpha3. and then release. You can surely have a preview before the end of the week.

**Comment by jtama** [comment]
Ok so I did the job, but waiting answers from [zulip](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkiverse.20extensions.20and.203.2E0), before breaking everything. Could you try building the extension you self from branch [prepare-v3](https://github.com/quarkiverse/quarkus-minio/tree/prepare-v3) ?

**Comment by jtama** [comment]
version 3.0.0.Alpha3 released !
