### ISSUE TITLE
Problems with fetching added metadata to a file 

### ISSUE THREAD

**Issue by corentin59** [quarkiverse/quarkus-minio#200]
### ISSUE
When I add metadata to a file, it will correctly store the metadata on minio console but incorrectly retrieve the metadata with minio client.

It's the same problem with that :
https://github.com/minio/minio/issues/15746#issue-1383864738

Version 2.10.3

Workaround available ?
Thx

**Comment by jtama** [comment]
I have to update the minio client version.
It's something that I have been post-poning for a long time as pull a new OKHTTP version and kotlin runtime with it... But this time I think I must face it ;)

**Comment by corentin59** [comment]
Good luck :)
For the moment I work with few files and I make a statobject which correctly returns the metadata

**Comment by jtama** [comment]
Will try do to it tomorrow, but I need to the work for 2.X and 3.X, so no promises.

**Comment by jtama** [comment]
this will soon be released for Quarkus 3.x branch, and we need to wait for 2.17 upstream to release for 2.X (https://github.com/quarkusio/quarkus/pull/30480)

**Comment by jtama** [comment]
So I released an updated version of the minio extension, but the okhttp is still enforced by the plateform so I have to rollback...
We'll keep you informed.

**Comment by corentin59** [comment]
Hi,

Upgrade in Quarkus 3.1.0.Final for me and the fixe is OK.
