### ISSUE TITLE
Migrate to the new Dev UI

### ISSUE THREAD

**Issue by phillip-kruger** [quarkiverse/quarkus-minio#208]
https://github.com/quarkusio/quarkus/issues/31315

**Comment by phillip-kruger** [comment]
@jtama is this something you can look at ? We are starting to plan the removal of the old Dev UI

**Comment by jtama** [comment]
Yes sorry for the delay. We are actually. Do you know have an estimate on when it should be removed ?

**Comment by phillip-kruger** [comment]
I am about to start work on that. So in the next release or maybe the one after that ...

**Comment by phillip-kruger** [comment]
I did an PR for the new Dev UI

**Comment by jtama** [comment]
Yes I have a question regarding the nbactions.xml file.

We wanted to add more details about potentials multiple minio client produced, but I guess, it's always better to start with you dev, and add more details after !

**Comment by jtama** [comment]
Many thanks !
