### ISSUE TITLE
Micrometer memory leak

### ISSUE THREAD

**Issue by paulthvt** [quarkiverse/quarkus-minio#249]
Hi all,

We are currently using the quarkus-minio client and once the quarkus micrometer extension is present on the server, we observe a memory leak.
According to the heap dump, the leak is caused by an accumulation of `io.micrometer.core.instrument.ImmutableTag`. 

![image](https://github.com/quarkiverse/quarkus-minio/assets/8106841/6a2eee2d-89c7-4e40-9ea5-b4f9d898bd58)

Those tags are not garbage collected and result in an application crash.
When disabling the metrics production on the minio client with [quarkus.minio.produce-metrics](https://docs.quarkiverse.io/quarkus-minio/dev/index.html#quarkus-minio_quarkus.minio.produce-metrics) we can't see the tags in the heap dump anymore and the application behaves normally. 

![image](https://github.com/quarkiverse/quarkus-minio/assets/8106841/25636d10-017d-4078-b0be-a6ce3c696e78)

Unless we missed a configuration somewhere, there a something wrong with those tags.
The micrometer documentation [suggest](https://github.com/micrometer-metrics/micrometer/issues/1830) to set a [MeterFilter#maximumAllowableTags()](https://www.javadoc.io/doc/io.micrometer/micrometer-core/1.0.3/io/micrometer/core/instrument/config/MeterFilter.html#maximumAllowableTags-java.lang.String-java.lang.String-int-io.micrometer.core.instrument.config.MeterFilter-) to prevent a memory leak. We saw that this has been already been done in the quarkus micrometer extension but maybe the minio client is missing something.

**Comment by jtama** [comment]
Ok I'll check this is most probably something I missed indeed.
Thanks for the report.

**Comment by jtama** [comment]
First of all, sorry for this very late answer, summer is not a good time for reactivity ;)

Could you either prepare a reproducer, or try using https://github.com/quarkiverse/quarkus-minio/tree/249-micrometer-memory-leak locally ?

**Comment by paulthvt** [comment]
Thanks for the reply. Unfortunately, I won't be able to provide any reproducer since I left the company a few days ago. I'll transfer your message to my former colleagues. I hope they'll be able to help you reproduce the issue.

**Comment by jtama** [comment]
Thanks for the forward and good luck for you new adventure !

**Comment by paulthvt** [comment]
> Thanks for the forward and good luck for you new adventure !

Thanks! 👍
