### ISSUE TITLE
Allow arbitrary env variables passed to the Min.io Dev Service

### ISSUE THREAD

**Issue by d135-1r43** [quarkiverse/quarkus-minio#321]
It is best practice to accept arbitrary env variables being passed to the dev service container. Examples for this can be found at the official Quarkus guide on Dev Services. E.g., `quarkus.amqp.devservices.container-env."environment-variable-name"`

Use case: I want the dev service to be preconfigured with

    ENV MINIO_NOTIFY_KAFKA_ENABLE_LOCAL="on"
    ENV MINIO_NOTIFY_KAFKA_BROKERS_LOCAL="localhost:55003"

If the feature gets approved, I could do the PR on my own.

**Comment by jtama** [comment]
Not 100% sure what you want to do. 
You wan't to be able to setup arbitrary env var that would be passed on to the dev service at startup ? In the example you give, they make use of `withEnv("AMQ_EXTRA_ARGS", extra);`, how exactcly would you reproduce that ?

Anyhow, please feel free to provide a PR, I would certainly have a better understanding of what you want to achieve.

**Comment by d135-1r43** [comment]
I made the PR and used the same pattern as the other extensions are using.

**Comment by jtama** [comment]
@d135-1r43 many thanks for your involvement, will release soon.
