### ISSUE TITLE
MinioAsyncClient configuration support

### ISSUE THREAD

**Issue by vemilyus** [quarkiverse/quarkus-minio#328]
Hi there,

have you thought about providing `MinioAsyncClient` instances next to the default blocking `MinioClient`?

I would find that really useful!

All the best,
Alex

**Comment by jtama** [comment]
I did not. Would you consider providing the PR yourself ?

**Comment by vemilyus** [comment]
Sure, I'll get right on it. Just wanted to touch base first ;)
