### ISSUE TITLE
Feature: Enhance client creation

### ISSUE THREAD

**Issue by JiriOndrusek** [quarkiverse/quarkus-minio#64]
Related to https://github.com/quarkiverse/quarkus-minio/issues/22

Would it be possible to change behavior of `MinioProducer`, so it would return `null` if all configuration properties are empty?

This behavior could be based on another property. For example if we introduce `quarkus.minio.nullableClient`
If `quarkus.minio.nullableClient` is `true` and no configuration properties are present, client producer would return `null`.
If it is false (default behavior) nothing would change.

Let me explain benefits of this behavior:

- it would allow users to define configuration properties and create client based on them (as is now)
- let say, that there is a library unaware of these properties, wrapper which adds quarkus to it could configure `quarkus.minio.nullableClient` to true. Library then may act based on the fact that the client is `null` and can define its own fallback.

This would help camel-quarkus minio extension (see https://github.com/apache/camel-quarkus/issues/2721)

**Comment by JiriOndrusek** [comment]
I can propose a PR if this idea is acceptable.

**Comment by JiriOndrusek** [comment]
I've tried to create this change and it is possible, you can see my prepared fix in commit : https://github.com/quarkiverse/quarkus-minio/commit/53b71edc67e8850ed9650a41196de876841f127f

I didn't create a PR, because it is not recommanded in project's README.md.

```
Contributions are always welcome, but this repository is not really ready for external contributions yet, better create an issue to discuss them prior to any contributions.
```

**Comment by jtama** [comment]
Ok, it fills the idea is acceptable, but in your sample code, there are not specific properties to allow empty configuration.

I'd better have an explicit `allowEmpty` config key. (as you said), and let default behaviour as is to help guide developer in case of missing conf.

Lastly I'm not sure if producing empty is a good thing.  The documentation says that if we do do so, we have to declare it `@Dependant` (https://docs.jboss.org/cdi/api/1.0/javax/enterprise/inject/Produces.html)

I will try to find time this week to take a closer l ook.

**Comment by JiriOndrusek** [comment]
@jtama thenks for the answer. You are right, my sample code doesn't include this property. It is merely a prove of concept, that it works (I tested it with our camel-quarkus tests and works successfully). I'll add this property `quarkus.minio.allowEmpty` and create a PR from it. @Dependent makes sense (based on the doc from the link). I'll try to add it to my PR.
